{% set version = "0.11.4" %}

package:
  name: pyhdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyhdf/pyhdf-{{ version }}.tar.gz
  sha256: f4d48ee6f297be76e07b1a31710ef898caa31757dfdf173e5a4b94988ea76164
  patches:
    - patches/turbojpeg_win.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - numpy
    - hdf4
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf4
    - zlib

test:
  imports:
    - pyhdf

about:
  home: https://github.com/fhs/pyhdf
  license: MIT
  license_file: LICENSE
  summary: Python interface to the NCSA HDF4 library

extra:
  recipe-maintainers:
    - ocefpaf
