{% set version = "0.9.10" %}

package:
  name: pyhdf
  version: {{ version }}

source:
  url: http://hdfeos.org/software/pyhdf/pyhdf-{{ version }}.tar.gz
  sha256: f1fd2d72838f30fc4e3a7688a4e1a395483b08e54f4955f3b4d384639e13c67a

build:
  number: 1000

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - hdf4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf4

test:
  imports:
    - pyhdf

about:
  home:  http://hdfeos.org/software/pyhdf
  license: Public Domain
  summary: 'Python interface to the NCSA HDF4 library.'

extra:
  recipe-maintainers:
      - ocefpaf
